reorder_impl_items = true
group_imports = "StdExternalCrate"
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
