#!/bin/bash

set -e

get_path() {
  if [ -L $1 ]; then
    readlink -f $1
  else
    echo $1
  fi
}

SCRIPT_PATH=$(get_path $0)
SCRIPT_DIR=$(cd $(dirname $SCRIPT_PATH) && pwd)
SCRIPT_NAME=$(basename $SCRIPT_PATH)
SYSROOT=$(cd $SCRIPT_DIR && rustc --print sysroot)
DIR=$SCRIPT_DIR SYSROOT=$SYSROOT LD_LIBRARY_PATH=$SYSROOT/lib \
  $SCRIPT_DIR/target/release/$SCRIPT_NAME $@
