name: CI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --check
      - name: Apply lints
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --release
      - name: Build dependency crate
        run: cd deps_crate && cargo build
